### ISSUE TITLE
"Can't reach this page"

### ISSUE THREAD

**Issue by shisuu** [pattontim/supermemo.js#3]
After following all instruction in the README, YouTube videos in SM do not load but rather shows "Can't reach this page" and "Make sure the web address https://localhost:8000 is correct".

Server is up and running in the background "Server listening on port 3000".

Since I don't have much knowledge in coding, I can't seem to figure it out.
Already played around with some port settings to no avail.

Looking forward to a solution! 
Also thanks for releasing this gem :)

**Comment by pattontim** [comment]
It should work with the latest fix. You appear to have done everything correctly, the issue was that the URL supermemo redirects to used the old server port 8000 but we're now using port 3000.

You need to replace YouTube.htm again and then restart SuperMemo.
