### ISSUE TITLE
Not supported video type or not valid file path

### ISSUE THREAD

**Issue by shisuuu** [pattontim/supermemo.js#4]
Good day!
Recently (today) I've been receiving following error when running the script:

mpd request for 2828AyYbUhA
error: SyntaxError: Unexpected token (1:47)
failed to get manifest

The YouTube video does not load anymore and I receive the following error:
"Not supported video type or not valid file path"

I updated to the most recent version.

**Comment by pattontim** [comment]
Hello thanks for using the plugin. This is a bug in the youtubei.js
library. A fix has been submitted so wait for a new release to be made


https://github.com/FreeTubeApp/FreeTube/issues/5378

**Comment by pattontim** [comment]
Fixed with commits 8abe6d4 and cb38dfe

Follow the instructions for updating in the REAMDE, especially steps 3+4
and new step 7 to clear cache
